export const TRAINING_CENTERS_STRINGS = {
  PAGE_TITLE: "Gestão de Performance",
  PAGE_DESCRIPTION: "Centro de treinamento esportivo de alta performance.",
  APPOINTMENTS_TITLE: "Agenda de Consultas",
  APPOINTMENTS_DESC: "Marque e gerencie consultas nutricionais.",
  ATHLETE_DATA_TITLE: "Dados dos Atletas",
  ATHLETE_DATA_DESC: "Adicione ou edite dados e acompanhe o progresso.",
  NUTRITIONAL_PLAN_TITLE: "Plano Alimentar",
  NUTRITIONAL_PLAN_DESC: "Cadastre novos planos nutricionais para atletas.",
  PERFORMANCE_TITLE: "Empenho e Performance",
  PERFORMANCE_DESC: "Monitoramento contínuo para resultados de elite.",
  SELECT_CLUB: "Selecione um Clube",
  SELECT_POSITION: "Selecione a Posição",
  ATHLETES_BY_CLUB: (clubName: string) => `Atletas - ${clubName}`,
  ATHLETES_BY_POSITION: (position: string) => `Atletas - ${position}`,
  ATHLETE_DETAILS: "Detalhes do Atleta",
  NO_CLUBS_FOUND: "Nenhum clube encontrado.",
  NO_CLUBS_DESC: "Certifique-se de que os clubes estão cadastrados corretamente.",
  NO_ATHLETES_FOUND: "Nenhum atleta encontrado para esta posição.",
  ERROR_FETCHING_DATA: "Erro ao buscar dados.",
  ERROR_FETCHING_DETAILS: "Erro ao buscar detalhes do atleta.",
  ERROR_REFRESHING_DATA: "Erro ao atualizar dados do atleta.",
};
