export const TRAINING_ROUTINE_STRINGS = {
  PAGE_TITLE: "Adicionar Rotina de Treinamento",
  PAGE_TITLE_FOR_CLUB: (clubName: string) => `Adicionar Rotina de Treinamento para ${clubName}`,
  PAGE_DESCRIPTION: "Preencha os detalhes para adicionar uma nova rotina de treinamento.",
  LOADING_CLUB: "Carregando informações do clube...",
  ERROR_LOADING_CLUB: (error: string) => `Erro ao carregar informações do clube: ${error}`,
  CLUB_NOT_FOUND: "Clube não encontrado.",
  FORM_CARD_TITLE: "Detalhes da Rotina",
  LABEL_ROUTINE_NAME: "Nome da Rotina",
  LABEL_DESCRIPTION: "Descrição",
  BUTTON_SUBMIT: "Adicionar Rotina",
  BUTTON_SUBMITTING: "Adicionando...",
  SUCCESS_TOAST_TITLE: "Sucesso!",
  SUCCESS_TOAST_DESCRIPTION: "Rotina de treinamento adicionada com sucesso.",
  ERROR_TOAST_TITLE: "Erro",
  ERROR_TOAST_DESCRIPTION: (error: string) => `Erro ao adicionar rotina de treinamento: ${error}`,
  
  // Routines List Page
  LIST_PAGE_TITLE: (centerName: string) => `Rotinas do CT ${centerName}`,
  BUTTON_ADD_NEW: "Adicionar Nova Rotina",
  MODAL_TITLE_CREATE: "Adicionar Nova Rotina",
  MODAL_TITLE_EDIT: "Editar Rotina",
  LABEL_DAY_OF_WEEK: "Dia da Semana",
  LABEL_TIME: "Horário",
  LABEL_ACTIVITY: "Atividade",
  PLACEHOLDER_DAY: "Selecione o dia",
  PLACEHOLDER_TIME: "Ex: 09:00-11:00",
  PLACEHOLDER_ACTIVITY: "Ex: Treino físico",
  PLACEHOLDER_DESCRIPTION: "Ex: Campo, academia, ou recuperação ativa",
  BUTTON_SAVE_CHANGES: "Salvar Alterações",
  BUTTON_EDIT: "Editar",
  BUTTON_DELETE: "Excluir",
  EMPTY_LIST_MESSAGE: "Nenhuma rotina de treinamento cadastrada para este clube.",
  AUTH_ERROR_TITLE: "Sessão expirada",
  AUTH_ERROR_DESCRIPTION: "Por favor, faça login novamente.",
  FETCH_CLUB_ERROR: "Falha ao carregar detalhes do clube.",
  FETCH_ROUTINES_ERROR: "Falha ao carregar rotinas de treinamento.",
  SAVE_SUCCESS_TITLE: "Sucesso",
  SAVE_SUCCESS_DESCRIPTION: (isEdit: boolean) => `Rotina de treinamento ${isEdit ? 'atualizada' : 'criada'} com sucesso!`,
  DELETE_SUCCESS_TITLE: "Sucesso",
  DELETE_SUCCESS_DESCRIPTION: "Rotina de treinamento excluída com sucesso!",
  DELETE_ERROR_MESSAGE: "Falha ao excluir rotina de treinamento.",
};
