export const NUTRITIONAL_CHATBOT_CONSTANTS = {
  TITLE: "Nova Consulta Nutricional",
  SUBTITLE: "IA Nutricionista - CBF Manager",
  HISTORY_BUTTON: "Consultas anteriores",
  MODELS_BUTTON: "Modelos",
  CLUB_LABEL: "Clube",
  CLUB_PLACEHOLDER: "Selecione o clube",
  ALL_CLUBS: "Todos os clubes",
  ATHLETE_LABEL: "Atleta",
  ATHLETE_PLACEHOLDER: "Selecione o atleta",
  PROFESSIONAL_LABEL: "Profissional Responsável",
  PROFESSIONAL_PLACEHOLDER: "Selecione o profissional",
  CONTEXT_LABEL: "Contexto do Paciente",
  CONTEXT_PLACEHOLDER: "Preencha este campo com informações clínicas do paciente: medicamentos, prontuários anteriores ou exames. Isso ajuda a fornecer um documento clínico mais completo.",
  MICROPHONE_HELP: "Habilite o microfone para gravar a consulta.",
  GENERATE_BUTTON: "Gerar Plano com IA",
  GENERATING_BUTTON: "Analisando...",
  GENERATED_PLAN_TITLE: "Plano Alimentar Gerado",
  CLEAR_BUTTON: "Limpar",
  EMPTY_PLAN_TITLE: "Nenhum plano gerado ainda",
  EMPTY_PLAN_DESCRIPTION: "Selecione um atleta e clique em \"Gerar Plano com IA\" para iniciar a análise nutricional.",
  HISTORY_MODAL_TITLE: "Histórico de Consultas",
  HISTORY_MODAL_DESCRIPTION: "Veja os planos nutricionais gerados anteriormente para este atleta.",
  NO_HISTORY_FOUND: "Nenhuma consulta anterior encontrada para este atleta.",
  DELETE_PLAN_CONFIRMATION: "Tem certeza que deseja excluir este plano nutricional?",
  IMAGE_URL: "https://i.ibb.co/qMTcDtrH/nutricao.webp",
  IMAGE_ALT: "Nutrição Esportiva",
  APPROVAL_TITLE: "APROVAÇÃO DO PROFISSIONAL",
  APPROVAL_TERMS: "TERMO DE APROVAÇÃO TÉCNICA",
  APPROVAL_STATUS: "APROVADO",
} as const;
