export const CREATE_APPOINTMENT_STRINGS = {
  TITLE_CREATE: "Agendar Nova Consulta",
  TITLE_EDIT: "Editar Consulta",
  DESCRIPTION_CREATE: "Preencha os dados abaixo para marcar uma nova consulta nutricional.",
  DESCRIPTION_EDIT: "Altere os detalhes da consulta selecionada.",
  CLUB_LABEL: "Clube",
  CLUB_PLACEHOLDER: "Selecione o clube",
  PROFESSIONAL_LABEL: "Profissional Responsável",
  PROFESSIONAL_PLACEHOLDER: "Selecione o profissional",
  ATHLETE_LABEL: "Atleta",
  ATHLETE_PLACEHOLDER: "Selecione o atleta",
  ATHLETE_DISABLED_PLACEHOLDER: "Selecione um clube primeiro",
  SERVICE_LABEL: "Serviço",
  SERVICE_PLACEHOLDER: "Tipo de consulta",
  LOCATION_LABEL: "Local",
  LOCATION_PLACEHOLDER: "Local de atendimento",
  DATE_LABEL: "Data",
  DATE_PLACEHOLDER: "Selecione a data",
  TIME_LABEL: "Horário",
  NOTES_LABEL: "Observações",
  NOTES_PLACEHOLDER: "Informações adicionais sobre a consulta...",
  CANCEL_BUTTON: "Cancelar",
  SUBMIT_CREATE: "Confirmar Agendamento",
  SUBMIT_EDIT: "Salvar Alterações",
  SUCCESS_CREATE: "Consulta agendada com sucesso!",
  SUCCESS_EDIT: "Consulta atualizada com sucesso!",
  ERROR_SUBMIT: "Não foi possível agendar a consulta.",
  FETCH_ERROR: "Erro ao buscar dados para o formulário",
} as const;
